---
title: "mercado_capitales_corte2"
author: "Juan Grimaldos"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# importacion de paquetes

```{r}
library(xts)
library(ggplot2)
library(quantmod)
library(dplyr)
library(magrittr)
library(plotly)
```





# test 

```{r}
library(readxl)
topix <- read_excel("C:/Users/POWER/OneDrive - unimilitar.edu.co/Trabajos/Semestre 9/mercap_2do_corte.xlsx", 
    sheet = "TOPIX_datos", range = "E1:F1038")
topix <- as.data.frame(topix)
topix$Fecha <- as.Date(format(topix$Fecha, "%Y-%m-%d"))
topix_xts <- as.xts(topix[,2], order.by = topix$Fecha)

chartSeries(topix_xts, TA=NULL)
```
```{r}

autoplot(topix_xts, geom = "line")
```
define custome them 

```{r}
# Define custom theme
my_theme <- function() {
  theme_bw() +
  theme(
    )
}
```



# TOPIX index
```{r}
library(readxl)
topix <- read_excel("data/mercap_2do_corte.xlsx", 
    sheet = "TOPIX_datos", range = "E1:F1038")
topix <- as.data.frame(topix)
topix$Fecha <- as.Date(format(topix$Fecha, "%Y-%m-%d"))
```



```{r}
library(plotly)
fig <- plot_ly(topix, type = 'scatter', mode = 'lines')%>%
  add_trace(x = ~Fecha, y = ~Cierre)%>%
  layout(showlegend = F)
fig <- fig %>%
  layout(
         xaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         yaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         plot_bgcolor='#e5ecf6', width = 900)


fig
detach("package:ggplot2", unload = TRUE)
```


```{r}
topix %>% 
  ggplot(mapping = aes(x = Fecha, y = Cierre)) +
  my_theme()+
  geom_line() +
  scale_y_continuous(breaks = seq(1000, 2500, by = 100))+
  scale_x_date(date_breaks = "6 month", date_labels = "%b %y")+
  geom_vline(xintercept = as.Date("2020-01-27"), color = "blue", linetype="longdash") +
  geom_vline(xintercept = as.Date("2021-01-27"), color = "blue", linetype="longdash") +
  labs(x ="", 
       y="TOPIX", 
       caption = "Fuente: Datos de Investopedia, elaboración propia")+
  annotate(geom = "text", x = as.Date("2019-08-27"), y = 1900, label = "Pre-COVID") +
  annotate(geom = "text", x = as.Date("2020-08-27"), y = 1900, label = "COVID") +
  annotate(geom = "text", x = as.Date("2022-08-27"), y = 1600, label = "post-COVID") +
  geom_label(data = topix %>% filter(Fecha == as.Date("2020-01-27")), 
             aes(label = Cierre), 
             size = 3, 
             color = "black", 
             fontface = "bold",
             nudge_y = 100
             )+
    geom_label(data = topix %>% filter(Fecha == as.Date("2021-09-14")), 
             aes(label = Cierre), 
             size = 3, 
             color = "black", 
             fontface = "bold",
             nudge_y = 50
             )+
      geom_label(data = topix %>% filter(Fecha == as.Date("2020-03-16")), 
             aes(label = Cierre), 
             size = 3, 
             color = "black", 
             fontface = "bold",
             nudge_y = -25,
             nudge_x = 25
             )
```




# FTSE 100

```{r}
getSymbols("^FTSE", src = "yahoo", )
```



# DJA

# Nikkei

